# Workflow for pushing updates from Github to Cloud Functions
name: GH_GCF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deploy CF
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ github.event.repository.name }}
          runtime: python37
          project_id: "api-project-901373404215"
          credentials: "-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCYPklIEzzZrbHT\n30jp5l/AdKaiQh5L25bEedzHdeOJtsxaFqdXppaKZZ0SsgnhMuN2d/Qyd8jS3XrN\nb102d9QHqCM7Kdh6Hito8igV/zwIo6iqdD0/afI0aEaRU/FMvHz80AZ/Ou1CcXIN\nO9+ehbzj6TFSbG2fkhHXmso0CwxG5RPRu99bnYZdiKy3J+uUzIRJ3WnGoXIP8iyH\n/khbI8WnmYOsbRv14JJNCT5sAUVQfJ1hDN85LRiSGxw+8kAzr+YVAsGmFjZIdaat\nf5fC+kwL344tzq+xr54/NHXJSXGI0qZqipQ1TGhUVIP93rHFz04yH789SzyjDfp/\nMFYjDUaBAgMBAAECgf8JucY/WdCZV1n03wluvSOAzUhCiqwaIdJlMCPFL5LJnr6P\nQsM4pjvCZkYShlfQkHUCLHI9McnH2Wju7B5YTG9keH6dA59WAyINd5V3/PDThyD5\n7VMRqgL/C2pL/mt71iQQl87ScevrmAkL2gypuSwdTdheG5nP3SpRS7d/JkrdJyFP\nwfHer7q8xsTzFD5JX3p7dDJFezMWYeUXC79AL7y/zfEHflJucHhrY/IdF5M3Ozuv\nL+TO88FDi7wMHVndDhRAyES75PtKVRxGMNVX+wwDxbOBQGw+GQOzfY7PCTDo0yMs\nhWfLMuWqDOxZjfNDT8HDDb9Rpd+NmBVaGaKw2AECgYEAzHvKsFXarTzpIFkYkB0o\n/SB7XCRTJL4cQ9bgtHvFeZ7+dPqchUXFq5/Q7/CLtkQkfHIY1Le3nKhg/L2qpx51\nbAaUsP5EkEfFZvGX9Gg+lowc0Xi2PLtubrkWFH2fD6/FDp6a9m6k3Vp+lF1rMKR7\nJJ0MWPHnspHX8tqI7MSWl4ECgYEAvpk/rYQyIRYYbmo3YsmhVebvueINiJNn9YQP\nfux5jUjZS1h/we7eJoWn/YrYrcami0MI/oKQ3U0Mp6rGF04jkZsys3VUTqVaE6tz\nKYA2aO8v3d9AD+nd79GzRhw3RF/RLigHKKn0dAIoDTu0RQxF1EtnZF/xU2Thtk6f\nIPumLwECgYEAg8p5XWNIOIVcf5PM5/1TUKmhuEZVLAY3c2XHl6t6ICPgPobTYHYS\nq8WqRSrU8RlEJszmwhrShW5kbCDWHzXbWk93gAexKwiG6w1k8YpKZH9Th5J0afon\nd8dkurooTVTs/botiAzRxzSvBnKbRlOMZpGtxpnKymWDOCuvOmKN6IECgYAnt9W+\nOfMcU/dpYvcBvhTByusf6Ex7roQWdJuqDmtSFuE5Q0r0RevDSUz1l+6JYAEquiBw\nsRKxGzJM6lh3WNAuspHBNe0Iqop32N2Zw18TROzLpo86Abk/FYrvTEf0FqeHn83G\nGoyXdC+Wel+Zl/IhSElWcGvgvgAPNpkQjYBXAQKBgEEPThYTjWnKnVpk56npARLN\nu/DVBzRqvbTSsx1tgbE6spuEhaylChhsaC7krKFs8GQjy8XRzgKoHENeptWxFXtI\nccYWpGWHLydMxaKfRukaGFHF20SehEmZBq/GWRYZ+2m5SWzcKH1eAWkMFL37Kq1I\nVIH4Xs/D3JvxDsOsdYgT\n-----END PRIVATE KEY-----\n"
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/api-project-901373404215/topics/${{ github.event.repository.name }}
          source_dir: ./function_files/
          timeout: 540
          memory_mb: 2048
